### ISSUE TITLE
I've forked it

### ISSUE THREAD

**Issue by denilsonsa** [ray-pH/vim-edir-syntax#1]
Hi! I just wanted to let you know I forked your syntax and then improved upon it: https://github.com/denilsonsa/vim-edir-syntax

(Well, at least I hope I have "improved" it.)

Feel free to merge back if you want to. I'd rather join forces and have one definitive syntax file, instead of spreading it over two or more projects. It also makes it easier for anyone looking for such syntax file.

**Comment by ray-pH** [comment]
Hi there! Thanks for forking my syntax project for edir and making improvements!

To be honest, I don't really use edir anymore, and I don't have any plans to continue working on this project. With that being the case, I think it's better to archive my repository and add a note in the README to direct users to your version. This way, users looking for the latest updates and improvements will have a clear path to your version, making it easier for everyone to find the most up-to-date syntax files.
